"""Static index constituent lists, needed by stages that score individual stocks
within an index (e.g. breadth confirmation).

There's no free, reliable API for index membership, so these lists are hand-populated
from a public source and refreshed periodically. CONSTITUENTS_SOURCE records where and
when each list was captured, so it's clear when a refresh is due (FTSE Russell reviews
FTSE 100 membership quarterly). If a suitable API/data source becomes available later,
swap the source here - stages only depend on INDEX_CONSTITUENTS, not on how it's built.
"""

CONSTITUENTS_SOURCE: dict[str, str] = {
    "^FTSE": "Wikipedia: en.wikipedia.org/wiki/FTSE_100_Index (captured 2026-08-15)",
    "^NDX": "Wikipedia: en.wikipedia.org/wiki/List_of_NASDAQ-100_companies (captured 2026-08-15)",
    "^DJI": "Wikipedia: en.wikipedia.org/wiki/Dow_Jones_Industrial_Average (captured 2026-08-15)",
    "^GDAXI": "Wikipedia: en.wikipedia.org/wiki/DAX (captured 2026-08-15)",
    "^FCHI": "Wikipedia: en.wikipedia.org/wiki/CAC_40 (captured 2026-08-15)",
    "^SSMI": "Wikipedia: en.wikipedia.org/wiki/Swiss_Market_Index (captured 2026-08-16)",
    "^STI": "Wikipedia: en.wikipedia.org/wiki/Straits_Times_Index (captured 2026-08-16)",
    "^IBEX": "Wikipedia: en.wikipedia.org/wiki/IBEX_35 (captured 2026-08-16)",
    "^NSEI": "Wikipedia: en.wikipedia.org/wiki/NIFTY_50 (captured 2026-08-16)",
    "^STOXX50E": "Wikipedia: en.wikipedia.org/wiki/EURO_STOXX_50 (captured 2026-08-16)",
}

# FTSE 100 constituents: Yahoo Finance ticker -> company name.
FTSE100_CONSTITUENTS: dict[str, str] = {
    "III.L": "3i",
    "ABDN.L": "Aberdeen Group",
    "ADM.L": "Admiral Group",
    "AAF.L": "Airtel Africa",
    "ALW.L": "Alliance Witan",
    "AAL.L": "Anglo American",
    "ANTO.L": "Antofagasta",
    "ABF.L": "Associated British Foods",
    "AZN.L": "AstraZeneca",
    "AUTO.L": "Autotrader Group",
    "AV.L": "Aviva",
    "BAB.L": "Babcock International",
    "BA.L": "BAE Systems",
    "BARC.L": "Barclays",
    "BTRW.L": "Barratt Redrow",
    "BEZ.L": "Beazley",
    "BP.L": "BP",
    "BATS.L": "British American Tobacco",
    "BLND.L": "British Land",
    "BT-A.L": "BT Group",
    "BNZL.L": "Bunzl",
    "BRBY.L": "Burberry Group",
    "CNA.L": "Centrica",
    "CCEP.L": "Coca-Cola Europacific Partners",
    "CCH.L": "Coca-Cola HBC",
    "CPG.L": "Compass Group",
    "CCC.L": "Computacenter",
    "CTEC.L": "Convatec",
    "CRDA.L": "Croda International",
    "DCC.L": "DCC",
    "DGE.L": "Diageo",
    "DPLM.L": "Diploma",
    "EDV.L": "Endeavour Mining",
    "ENT.L": "Entain",
    "EXPN.L": "Experian",
    "FCIT.L": "F&C Investment Trust",
    "FRES.L": "Fresnillo",
    "GAW.L": "Games Workshop",
    "GLEN.L": "Glencore",
    "GSK.L": "GSK",
    "HLN.L": "Haleon",
    "HLMA.L": "Halma",
    "HSX.L": "Hiscox",
    "HWDN.L": "Howdens Joinery",
    "HSBA.L": "HSBC",
    "ICG.L": "ICG",
    "IGG.L": "IG Group",
    "IHG.L": "IHG Hotels & Resorts",
    "IMI.L": "IMI",
    "IMB.L": "Imperial Brands",
    "INF.L": "Informa",
    "IAG.L": "International Airlines Group",
    "ITRK.L": "Intertek",
    "INVP.L": "Investec",
    "JD.L": "JD Sports",
    "BGEO.L": "Lion Finance Group",
    "KGF.L": "Kingfisher",
    "LAND.L": "Land Securities",
    "LGEN.L": "Legal & General",
    "LLOY.L": "Lloyds Banking Group",
    "LMP.L": "LondonMetric Property",
    "LSEG.L": "London Stock Exchange Group",
    "MNG.L": "M&G",
    "MKS.L": "Marks & Spencer",
    "MRO.L": "Melrose Industries",
    "MTLN.L": "Metlen Energy & Metals",
    "NG.L": "National Grid",
    "NWG.L": "NatWest Group",
    "NXT.L": "Next",
    "PSON.L": "Pearson",
    "PSH.L": "Pershing Square Holdings",
    "PSN.L": "Persimmon",
    "PCT.L": "Polar Capital Technology Trust",
    "PRU.L": "Prudential",
    "RKT.L": "Reckitt",
    "REL.L": "RELX",
    "RTO.L": "Rentokil Initial",
    "RIO.L": "Rio Tinto",
    "RR.L": "Rolls-Royce Holdings",
    "SGE.L": "Sage Group",
    "SBRY.L": "Sainsbury's",
    "SDR.L": "Schroders",
    "SMT.L": "Scottish Mortgage Investment Trust",
    "SGRO.L": "Segro",
    "SVT.L": "Severn Trent",
    "SHEL.L": "Shell",
    "SMIN.L": "Smiths Group",
    "SN.L": "Smith & Nephew",
    "SPX.L": "Spirax Group",
    "SSE.L": "SSE",
    "STAN.L": "Standard Chartered",
    "SDLF.L": "Standard Life",
    "STJ.L": "St. James's Place",
    "TSCO.L": "Tesco",
    "BBOX.L": "Tritax Big Box REIT",
    "ULVR.L": "Unilever",
    "UU.L": "United Utilities",
    "VOD.L": "Vodafone Group",
    "WEIR.L": "Weir",
    "WTB.L": "Whitbread",
}

# Nasdaq-100 constituents: Yahoo Finance ticker -> company name.
# Yahoo lists these US tickers as-is, no exchange suffix needed (unlike LSE's .L).
NDX100_CONSTITUENTS: dict[str, str] = {
    "ADBE": "Adobe",
    "AMD": "Advanced Micro Devices",
    "ABNB": "Airbnb",
    "ALNY": "Alnylam Pharmaceuticals",
    "GOOGL": "Alphabet (Class A)",
    "GOOG": "Alphabet (Class C)",
    "AMZN": "Amazon",
    "AEP": "American Electric Power",
    "AMGN": "Amgen",
    "ADI": "Analog Devices",
    "AAPL": "Apple",
    "AMAT": "Applied Materials",
    "APP": "AppLovin",
    "ARM": "Arm Holdings",
    "ASML": "ASML Holding",
    "ALAB": "Astera Labs",
    "ADSK": "Autodesk",
    "ADP": "Automatic Data Processing",
    "AXON": "Axon Enterprise",
    "BKR": "Baker Hughes",
    "BKNG": "Booking Holdings",
    "AVGO": "Broadcom",
    "CDNS": "Cadence Design Systems",
    "CTAS": "Cintas",
    "CSCO": "Cisco",
    "CCEP": "Coca-Cola Europacific Partners",
    "CMCSA": "Comcast",
    "CEG": "Constellation Energy",
    "CPRT": "Copart",
    "CRWV": "CoreWeave",
    "COST": "Costco",
    "CRWD": "CrowdStrike",
    "CSX": "CSX Corporation",
    "DDOG": "Datadog",
    "DXCM": "DexCom",
    "FANG": "Diamondback Energy",
    "DASH": "DoorDash",
    "EXC": "Exelon",
    "FAST": "Fastenal",
    "FER": "Ferrovial",
    "FTNT": "Fortinet",
    "GEHC": "GE HealthCare",
    "GILD": "Gilead Sciences",
    "HONA": "Honeywell Aerospace",
    "HON": "Honeywell Technologies",
    "IDXX": "Idexx Laboratories",
    "INTC": "Intel",
    "INTU": "Intuit",
    "ISRG": "Intuitive Surgical",
    "KDP": "Keurig Dr Pepper",
    "KLAC": "KLA Corporation",
    "KHC": "Kraft Heinz",
    "LRCX": "Lam Research",
    "LIN": "Linde",
    "LITE": "Lumentum",
    "MAR": "Marriott International",
    "MRVL": "Marvell Technology",
    "MELI": "Mercado Libre",
    "META": "Meta Platforms",
    "MCHP": "Microchip Technology",
    "MU": "Micron Technology",
    "MSFT": "Microsoft",
    "MSTR": "MicroStrategy",
    "MDLZ": "Mondelez International",
    "MPWR": "Monolithic Power Systems",
    "MNST": "Monster Beverage",
    "NBIS": "Nebius Group",
    "NFLX": "Netflix",
    "NVDA": "Nvidia",
    "NXPI": "NXP Semiconductors",
    "ORLY": "O'Reilly Automotive",
    "ODFL": "Old Dominion Freight Line",
    "PCAR": "Paccar",
    "PLTR": "Palantir Technologies",
    "PANW": "Palo Alto Networks",
    "PAYX": "Paychex",
    "PYPL": "PayPal",
    "PDD": "PDD Holdings",
    "PEP": "PepsiCo",
    "QCOM": "Qualcomm",
    "REGN": "Regeneron Pharmaceuticals",
    "RKLB": "Rocket Lab",
    "ROP": "Roper Technologies",
    "ROST": "Ross Stores",
    "SNDK": "Sandisk",
    "STX": "Seagate Technology",
    "SHOP": "Shopify",
    "SPCX": "SpaceX",
    "SBUX": "Starbucks",
    "SNPS": "Synopsys",
    "TMUS": "T-Mobile US",
    "TTWO": "Take-Two Interactive",
    "TER": "Teradyne",
    "TSLA": "Tesla",
    "TXN": "Texas Instruments",
    "TRI": "Thomson Reuters",
    "VRTX": "Vertex Pharmaceuticals",
    "WMT": "Walmart",
    "WBD": "Warner Bros. Discovery",
    "WDC": "Western Digital",
    "WDAY": "Workday",
    "XEL": "Xcel Energy",
}

# Dow Jones Industrial Average constituents: Yahoo Finance ticker -> company name.
DJI30_CONSTITUENTS: dict[str, str] = {
    "MMM": "3M",
    "GOOGL": "Alphabet",
    "AMZN": "Amazon",
    "AXP": "American Express",
    "AMGN": "Amgen",
    "AAPL": "Apple",
    "BA": "Boeing",
    "CAT": "Caterpillar",
    "CVX": "Chevron",
    "CSCO": "Cisco",
    "KO": "Coca-Cola",
    "DIS": "Disney",
    "GS": "Goldman Sachs",
    "HD": "Home Depot",
    "HON": "Honeywell Technologies",
    "IBM": "IBM",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "MCD": "McDonald's",
    "MRK": "Merck",
    "MSFT": "Microsoft",
    "NKE": "Nike",
    "NVDA": "Nvidia",
    "PG": "Procter & Gamble",
    "CRM": "Salesforce",
    "SHW": "Sherwin-Williams",
    "TRV": "Travelers",
    "UNH": "UnitedHealth",
    "V": "Visa",
    "WMT": "Walmart",
}

# DAX constituents: Yahoo Finance ticker -> company name.
DAX_CONSTITUENTS: dict[str, str] = {
    "ADS.DE": "Adidas",
    "AIR.PA": "Airbus",
    "ALV.DE": "Allianz",
    "BAS.DE": "BASF",
    "BAYN.DE": "Bayer",
    "BEI.DE": "Beiersdorf",
    "BMW.DE": "BMW",
    "BNR.DE": "Brenntag",
    "CBK.DE": "Commerzbank",
    "CON.DE": "Continental",
    "DTG.DE": "Daimler Truck",
    "DBK.DE": "Deutsche Bank",
    "DB1.DE": "Deutsche Börse",
    "DHL.DE": "Deutsche Post",
    "DTE.DE": "Deutsche Telekom",
    "EOAN.DE": "E.ON",
    "FRE.DE": "Fresenius",
    "FME.DE": "Fresenius Medical Care",
    "G1A.DE": "GEA Group",
    "HNR1.DE": "Hannover Re",
    "HEI.DE": "Heidelberg Materials",
    "HEN3.DE": "Henkel",
    "IFX.DE": "Infineon Technologies",
    "MBG.DE": "Mercedes-Benz Group",
    "MRK.DE": "Merck",
    "MTX.DE": "MTU Aero Engines",
    "MUV2.DE": "Munich Re",
    "PAH3.DE": "Porsche SE",
    "QIA.DE": "Qiagen",
    "RHM.DE": "Rheinmetall",
    "RWE.DE": "RWE",
    "SAP.DE": "SAP",
    "G24.DE": "Scout24",
    "SIE.DE": "Siemens",
    "ENR.DE": "Siemens Energy",
    "SHL.DE": "Siemens Healthineers",
    "SY1.DE": "Symrise",
    "VOW3.DE": "Volkswagen Group",
    "VNA.DE": "Vonovia",
    "ZAL.DE": "Zalando",
}

# CAC 40 constituents: Yahoo Finance ticker -> company name.
CAC40_CONSTITUENTS: dict[str, str] = {
    "AC.PA": "Accor",
    "AI.PA": "Air Liquide",
    "AIR.PA": "Airbus",
    "MT.AS": "ArcelorMittal",
    "CS.PA": "Axa",
    "BNP.PA": "BNP Paribas",
    "EN.PA": "Bouygues",
    "BVI.PA": "Bureau Veritas",
    "CAP.PA": "Capgemini",
    "CA.PA": "Carrefour",
    "ACA.PA": "Crédit Agricole",
    "BN.PA": "Danone",
    "DSY.PA": "Dassault Systèmes",
    "EDEN.PA": "Edenred",
    "ENGI.PA": "Engie",
    "EL.PA": "EssilorLuxottica",
    "ERF.PA": "Eurofins Scientific",
    "RMS.PA": "Hermès",
    "KER.PA": "Kering",
    "OR.PA": "L'Oréal",
    "LR.PA": "Legrand",
    "MC.PA": "LVMH",
    "ML.PA": "Michelin",
    "ORA.PA": "Orange",
    "RI.PA": "Pernod Ricard",
    "PUB.PA": "Publicis",
    "RNO.PA": "Renault",
    "SAF.PA": "Safran",
    "SGO.PA": "Saint-Gobain",
    "SAN.PA": "Sanofi",
    "SU.PA": "Schneider Electric",
    "GLE.PA": "Société Générale",
    "STLAP.PA": "Stellantis",
    "STMPA.PA": "STMicroelectronics",
    "TEP.PA": "Teleperformance",
    "HO.PA": "Thales",
    "TTE.PA": "TotalEnergies",
    "URW.PA": "Unibail-Rodamco-Westfield",
    "VIE.PA": "Veolia",
    "DG.PA": "Vinci",
}

# Swiss Market Index constituents: Yahoo Finance ticker -> company name.
# Roche's SMI-listed security is its participation certificate (ROP); ROG, despite
# widely-cited references to it, returns no live data on Yahoo - verified by fetch.
SSMI_CONSTITUENTS: dict[str, str] = {
    "NOVN.SW": "Novartis",
    "ROP.SW": "Roche Holding",
    "NESN.SW": "Nestlé",
    "ABBN.SW": "ABB",
    "UBSG.SW": "UBS Group",
    "CFR.SW": "Compagnie Financière Richemont",
    "ZURN.SW": "Zurich Insurance Group",
    "HOLN.SW": "Holcim",
    "SREN.SW": "Swiss Reinsurance",
    "LONN.SW": "Lonza Group",
    "SCMN.SW": "Swisscom",
    "GIVN.SW": "Givaudan",
    "ALC.SW": "Alcon",
    "SIKA.SW": "Sika",
    "AMRZ.SW": "Amrize",
    "SLHN.SW": "Swiss Life Holding",
    "KNIN.SW": "Kuehne + Nagel",
    "GEBN.SW": "Geberit",
    "PGHN.SW": "Partners Group Holding",
    "LOGN.SW": "Logitech International",
}

# Straits Times Index constituents: Yahoo Finance ticker -> company name.
STI_CONSTITUENTS: dict[str, str] = {
    "A17U.SI": "CapitaLand Ascendas REIT",
    "C38U.SI": "CapitaLand Integrated Commercial Trust",
    "9CI.SI": "CapitaLand Investment",
    "C09.SI": "City Developments",
    "D05.SI": "DBS Group Holdings",
    "D01.SI": "DFI Retail Group Holdings",
    "J69U.SI": "Frasers Centrepoint Trust",
    "BUOU.SI": "Frasers Logistics & Commercial Trust",
    "G13.SI": "Genting Singapore",
    "H78.SI": "Hongkong Land Holdings",
    "J36.SI": "Jardine Matheson Holdings",
    "BN4.SI": "Keppel Corporation",
    "AJBU.SI": "Keppel DC REIT",
    "ME8U.SI": "Mapletree Industrial Trust",
    "M44U.SI": "Mapletree Logistics Trust",
    "N2IU.SI": "Mapletree Pan Asia Commercial Trust",
    "O39.SI": "OCBC Bank",
    "S58.SI": "SATS",
    "5E2.SI": "Seatrium",
    "U96.SI": "Sembcorp Industries",
    "C6L.SI": "Singapore Airlines",
    "S68.SI": "Singapore Exchange",
    "Z74.SI": "Singtel",
    "S63.SI": "Singapore Technologies Engineering",
    "Y92.SI": "Thai Beverages",
    "U11.SI": "United Overseas Bank",
    "U14.SI": "UOL Group",
    "V03.SI": "Venture Corporation",
    "F34.SI": "Wilmar International",
    "BS6.SI": "Yangzijiang Shipbuilding Holdings",
}

# IBEX 35 constituents: Yahoo Finance ticker -> company name.
IBEX35_CONSTITUENTS: dict[str, str] = {
    "ACS.MC": "ACS",
    "ACX.MC": "Acerinox",
    "AMS.MC": "Amadeus IT Group",
    "ANA.MC": "Acciona",
    "ANE.MC": "Acciona Energía",
    "BBVA.MC": "BBVA",
    "BKT.MC": "Bankinter",
    "CABK.MC": "CaixaBank",
    "CLNX.MC": "Cellnex Telecom",
    "COL.MC": "Inmobiliaria Colonial",
    "AENA.MC": "AENA",
    "ELE.MC": "Endesa",
    "ENG.MC": "Enagás",
    "FDR.MC": "Fluidra",
    "FER.MC": "Ferrovial",
    "GRF.MC": "Grifols",
    "IAG.MC": "International Airlines Group",
    "IBE.MC": "Iberdrola",
    "IDR.MC": "Indra",
    "ITX.MC": "Inditex",
    "LOG.MC": "Logista",
    "MAP.MC": "Mapfre",
    "MRL.MC": "Merlin Properties",
    "MTS.MC": "ArcelorMittal",
    "NTGY.MC": "Naturgy",
    "PUIG.MC": "Puig",
    "RED.MC": "Redeia Corporación",
    "REP.MC": "Repsol",
    "ROVI.MC": "Laboratorios Rovi",
    "SAB.MC": "Banco Sabadell",
    "SAN.MC": "Banco Santander",
    "SCYR.MC": "Sacyr",
    "SLR.MC": "Solaria",
    "TEF.MC": "Telefónica",
    "UNI.MC": "Unicaja",
}

# Nifty 50 constituents: Yahoo Finance ticker -> company name.
NIFTY50_CONSTITUENTS: dict[str, str] = {
    "ADANIENT.NS": "Adani Enterprises",
    "ADANIPORTS.NS": "Adani Ports & SEZ",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "ASIANPAINT.NS": "Asian Paints",
    "AXISBANK.NS": "Axis Bank",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "BAJFINANCE.NS": "Bajaj Finance",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "BEL.NS": "Bharat Electronics",
    "BHARTIARTL.NS": "Bharti Airtel",
    "CIPLA.NS": "Cipla",
    "COALINDIA.NS": "Coal India",
    "DRREDDY.NS": "Dr. Reddy's Laboratories",
    "EICHERMOT.NS": "Eicher Motors",
    "ETERNAL.NS": "Eternal",
    "GRASIM.NS": "Grasim Industries",
    "HCLTECH.NS": "HCLTech",
    "HDFCBANK.NS": "HDFC Bank",
    "HDFCLIFE.NS": "HDFC Life",
    "HINDALCO.NS": "Hindalco Industries",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "ICICIBANK.NS": "ICICI Bank",
    "INDIGO.NS": "IndiGo",
    "INFY.NS": "Infosys",
    "ITC.NS": "ITC",
    "JIOFIN.NS": "Jio Financial Services",
    "JSWSTEEL.NS": "JSW Steel",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "LT.NS": "Larsen & Toubro",
    "M&M.NS": "Mahindra & Mahindra",
    "MARUTI.NS": "Maruti Suzuki",
    "MAXHEALTH.NS": "Max Healthcare",
    "NESTLEIND.NS": "Nestlé India",
    "NTPC.NS": "NTPC",
    "ONGC.NS": "Oil and Natural Gas Corporation",
    "POWERGRID.NS": "Power Grid",
    "RELIANCE.NS": "Reliance Industries",
    "SBILIFE.NS": "SBI Life Insurance",
    "SHRIRAMFIN.NS": "Shriram Finance",
    "SBIN.NS": "State Bank of India",
    "SUNPHARMA.NS": "Sun Pharma",
    "TCS.NS": "Tata Consultancy Services",
    "TATACONSUM.NS": "Tata Consumer Products",
    "TMPV.NS": "Tata Motors Passenger Vehicles",
    "TATASTEEL.NS": "Tata Steel",
    "TECHM.NS": "Tech Mahindra",
    "TITAN.NS": "Titan Company",
    "TRENT.NS": "Trent",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "WIPRO.NS": "Wipro",
}

# Euro Stoxx 50 constituents: Yahoo Finance ticker -> company name.
STOXX50E_CONSTITUENTS: dict[str, str] = {
    "ADS.DE": "Adidas",
    "ADYEN.AS": "Adyen",
    "AD.AS": "Ahold Delhaize",
    "AI.PA": "Air Liquide",
    "AIR.PA": "Airbus",
    "ALV.DE": "Allianz",
    "ABI.BR": "Anheuser-Busch InBev",
    "ARGX.BR": "Argenx",
    "ASML.AS": "ASML Holding",
    "CS.PA": "Axa",
    "BAS.DE": "BASF",
    "BAYN.DE": "Bayer",
    "BBVA.MC": "BBVA",
    "SAN.MC": "Banco Santander",
    "BMW.DE": "BMW",
    "BNP.PA": "BNP Paribas",
    "BN.PA": "Danone",
    "DBK.DE": "Deutsche Bank",
    "DB1.DE": "Deutsche Börse",
    "DHL.DE": "Deutsche Post",
    "DTE.DE": "Deutsche Telekom",
    "ENEL.MI": "Enel",
    "ENI.MI": "Eni",
    "EL.PA": "EssilorLuxottica",
    "RACE.MI": "Ferrari",
    "RMS.PA": "Hermès",
    "IBE.MC": "Iberdrola",
    "ITX.MC": "Inditex",
    "IFX.DE": "Infineon Technologies",
    "INGA.AS": "ING Group",
    "ISP.MI": "Intesa Sanpaolo",
    "OR.PA": "L'Oréal",
    "MC.PA": "LVMH",
    "MBG.DE": "Mercedes-Benz Group",
    "MUV2.DE": "Munich Re",
    "NDA-FI.HE": "Nordea",
    "PRX.AS": "Prosus",
    "RHM.DE": "Rheinmetall",
    "SAF.PA": "Safran",
    "SGO.PA": "Saint-Gobain",
    "SAN.PA": "Sanofi",
    "SAP.DE": "SAP",
    "SU.PA": "Schneider Electric",
    "SIE.DE": "Siemens",
    "ENR.DE": "Siemens Energy",
    "TTE.PA": "TotalEnergies",
    "DG.PA": "Vinci",
    "UCG.MI": "UniCredit",
    "VOW.DE": "Volkswagen Group",
    "WKL.AS": "Wolters Kluwer",
}

# Registry: parent index ticker -> its constituents' Yahoo tickers.
# Only indices listed here support constituent-level stages (e.g. breadth confirmation).
INDEX_CONSTITUENTS: dict[str, list[str]] = {
    "^FTSE": list(FTSE100_CONSTITUENTS),
    "^NDX": list(NDX100_CONSTITUENTS),
    "^DJI": list(DJI30_CONSTITUENTS),
    "^GDAXI": list(DAX_CONSTITUENTS),
    "^FCHI": list(CAC40_CONSTITUENTS),
    "^SSMI": list(SSMI_CONSTITUENTS),
    "^STI": list(STI_CONSTITUENTS),
    "^IBEX": list(IBEX35_CONSTITUENTS),
    "^NSEI": list(NIFTY50_CONSTITUENTS),
    "^STOXX50E": list(STOXX50E_CONSTITUENTS),
}

# ticker -> name, across all populated indices, for display purposes.
CONSTITUENT_NAMES: dict[str, str] = {
    **FTSE100_CONSTITUENTS,
    **NDX100_CONSTITUENTS,
    **DJI30_CONSTITUENTS,
    **DAX_CONSTITUENTS,
    **CAC40_CONSTITUENTS,
    **SSMI_CONSTITUENTS,
    **STI_CONSTITUENTS,
    **IBEX35_CONSTITUENTS,
    **NIFTY50_CONSTITUENTS,
    **STOXX50E_CONSTITUENTS,
}
