"""Static index constituent lists, needed by stages that score individual stocks
within an index (e.g. breadth confirmation).

There's no free, reliable API for index membership, so these lists are hand-populated
from a public source and refreshed periodically. CONSTITUENTS_SOURCE records where and
when each list was captured, so it's clear when a refresh is due (FTSE Russell reviews
FTSE 100 membership quarterly). If a suitable API/data source becomes available later,
swap the source here - stages only depend on INDEX_CONSTITUENTS, not on how it's built.
"""

CONSTITUENTS_SOURCE: dict[str, str] = {
    "^FTSE": "Wikipedia: en.wikipedia.org/wiki/FTSE_100_Index (captured 2026-08-15)",
    "^NDX": "Wikipedia: en.wikipedia.org/wiki/List_of_NASDAQ-100_companies (captured 2026-08-15)",
    "^DJI": "Wikipedia: en.wikipedia.org/wiki/Dow_Jones_Industrial_Average (captured 2026-08-15)",
    "^GDAXI": "Wikipedia: en.wikipedia.org/wiki/DAX (captured 2026-08-15)",
    "^FCHI": "Wikipedia: en.wikipedia.org/wiki/CAC_40 (captured 2026-08-15)",
}

# FTSE 100 constituents: Yahoo Finance ticker -> company name.
FTSE100_CONSTITUENTS: dict[str, str] = {
    "III.L": "3i",
    "ABDN.L": "Aberdeen Group",
    "ADM.L": "Admiral Group",
    "AAF.L": "Airtel Africa",
    "ALW.L": "Alliance Witan",
    "AAL.L": "Anglo American",
    "ANTO.L": "Antofagasta",
    "ABF.L": "Associated British Foods",
    "AZN.L": "AstraZeneca",
    "AUTO.L": "Autotrader Group",
    "AV.L": "Aviva",
    "BAB.L": "Babcock International",
    "BA.L": "BAE Systems",
    "BARC.L": "Barclays",
    "BTRW.L": "Barratt Redrow",
    "BEZ.L": "Beazley",
    "BP.L": "BP",
    "BATS.L": "British American Tobacco",
    "BLND.L": "British Land",
    "BT-A.L": "BT Group",
    "BNZL.L": "Bunzl",
    "BRBY.L": "Burberry Group",
    "CNA.L": "Centrica",
    "CCEP.L": "Coca-Cola Europacific Partners",
    "CCH.L": "Coca-Cola HBC",
    "CPG.L": "Compass Group",
    "CCC.L": "Computacenter",
    "CTEC.L": "Convatec",
    "CRDA.L": "Croda International",
    "DCC.L": "DCC",
    "DGE.L": "Diageo",
    "DPLM.L": "Diploma",
    "EDV.L": "Endeavour Mining",
    "ENT.L": "Entain",
    "EXPN.L": "Experian",
    "FCIT.L": "F&C Investment Trust",
    "FRES.L": "Fresnillo",
    "GAW.L": "Games Workshop",
    "GLEN.L": "Glencore",
    "GSK.L": "GSK",
    "HLN.L": "Haleon",
    "HLMA.L": "Halma",
    "HSX.L": "Hiscox",
    "HWDN.L": "Howdens Joinery",
    "HSBA.L": "HSBC",
    "ICG.L": "ICG",
    "IGG.L": "IG Group",
    "IHG.L": "IHG Hotels & Resorts",
    "IMI.L": "IMI",
    "IMB.L": "Imperial Brands",
    "INF.L": "Informa",
    "IAG.L": "International Airlines Group",
    "ITRK.L": "Intertek",
    "INVP.L": "Investec",
    "JD.L": "JD Sports",
    "BGEO.L": "Lion Finance Group",
    "KGF.L": "Kingfisher",
    "LAND.L": "Land Securities",
    "LGEN.L": "Legal & General",
    "LLOY.L": "Lloyds Banking Group",
    "LMP.L": "LondonMetric Property",
    "LSEG.L": "London Stock Exchange Group",
    "MNG.L": "M&G",
    "MKS.L": "Marks & Spencer",
    "MRO.L": "Melrose Industries",
    "MTLN.L": "Metlen Energy & Metals",
    "NG.L": "National Grid",
    "NWG.L": "NatWest Group",
    "NXT.L": "Next",
    "PSON.L": "Pearson",
    "PSH.L": "Pershing Square Holdings",
    "PSN.L": "Persimmon",
    "PCT.L": "Polar Capital Technology Trust",
    "PRU.L": "Prudential",
    "RKT.L": "Reckitt",
    "REL.L": "RELX",
    "RTO.L": "Rentokil Initial",
    "RIO.L": "Rio Tinto",
    "RR.L": "Rolls-Royce Holdings",
    "SGE.L": "Sage Group",
    "SBRY.L": "Sainsbury's",
    "SDR.L": "Schroders",
    "SMT.L": "Scottish Mortgage Investment Trust",
    "SGRO.L": "Segro",
    "SVT.L": "Severn Trent",
    "SHEL.L": "Shell",
    "SMIN.L": "Smiths Group",
    "SN.L": "Smith & Nephew",
    "SPX.L": "Spirax Group",
    "SSE.L": "SSE",
    "STAN.L": "Standard Chartered",
    "SDLF.L": "Standard Life",
    "STJ.L": "St. James's Place",
    "TSCO.L": "Tesco",
    "BBOX.L": "Tritax Big Box REIT",
    "ULVR.L": "Unilever",
    "UU.L": "United Utilities",
    "VOD.L": "Vodafone Group",
    "WEIR.L": "Weir",
    "WTB.L": "Whitbread",
}

# Nasdaq-100 constituents: Yahoo Finance ticker -> company name.
# Yahoo lists these US tickers as-is, no exchange suffix needed (unlike LSE's .L).
NDX100_CONSTITUENTS: dict[str, str] = {
    "ADBE": "Adobe",
    "AMD": "Advanced Micro Devices",
    "ABNB": "Airbnb",
    "ALNY": "Alnylam Pharmaceuticals",
    "GOOGL": "Alphabet (Class A)",
    "GOOG": "Alphabet (Class C)",
    "AMZN": "Amazon",
    "AEP": "American Electric Power",
    "AMGN": "Amgen",
    "ADI": "Analog Devices",
    "AAPL": "Apple",
    "AMAT": "Applied Materials",
    "APP": "AppLovin",
    "ARM": "Arm Holdings",
    "ASML": "ASML Holding",
    "ALAB": "Astera Labs",
    "ADSK": "Autodesk",
    "ADP": "Automatic Data Processing",
    "AXON": "Axon Enterprise",
    "BKR": "Baker Hughes",
    "BKNG": "Booking Holdings",
    "AVGO": "Broadcom",
    "CDNS": "Cadence Design Systems",
    "CTAS": "Cintas",
    "CSCO": "Cisco",
    "CCEP": "Coca-Cola Europacific Partners",
    "CMCSA": "Comcast",
    "CEG": "Constellation Energy",
    "CPRT": "Copart",
    "CRWV": "CoreWeave",
    "COST": "Costco",
    "CRWD": "CrowdStrike",
    "CSX": "CSX Corporation",
    "DDOG": "Datadog",
    "DXCM": "DexCom",
    "FANG": "Diamondback Energy",
    "DASH": "DoorDash",
    "EXC": "Exelon",
    "FAST": "Fastenal",
    "FER": "Ferrovial",
    "FTNT": "Fortinet",
    "GEHC": "GE HealthCare",
    "GILD": "Gilead Sciences",
    "HONA": "Honeywell Aerospace",
    "HON": "Honeywell Technologies",
    "IDXX": "Idexx Laboratories",
    "INTC": "Intel",
    "INTU": "Intuit",
    "ISRG": "Intuitive Surgical",
    "KDP": "Keurig Dr Pepper",
    "KLAC": "KLA Corporation",
    "KHC": "Kraft Heinz",
    "LRCX": "Lam Research",
    "LIN": "Linde",
    "LITE": "Lumentum",
    "MAR": "Marriott International",
    "MRVL": "Marvell Technology",
    "MELI": "Mercado Libre",
    "META": "Meta Platforms",
    "MCHP": "Microchip Technology",
    "MU": "Micron Technology",
    "MSFT": "Microsoft",
    "MSTR": "MicroStrategy",
    "MDLZ": "Mondelez International",
    "MPWR": "Monolithic Power Systems",
    "MNST": "Monster Beverage",
    "NBIS": "Nebius Group",
    "NFLX": "Netflix",
    "NVDA": "Nvidia",
    "NXPI": "NXP Semiconductors",
    "ORLY": "O'Reilly Automotive",
    "ODFL": "Old Dominion Freight Line",
    "PCAR": "Paccar",
    "PLTR": "Palantir Technologies",
    "PANW": "Palo Alto Networks",
    "PAYX": "Paychex",
    "PYPL": "PayPal",
    "PDD": "PDD Holdings",
    "PEP": "PepsiCo",
    "QCOM": "Qualcomm",
    "REGN": "Regeneron Pharmaceuticals",
    "RKLB": "Rocket Lab",
    "ROP": "Roper Technologies",
    "ROST": "Ross Stores",
    "SNDK": "Sandisk",
    "STX": "Seagate Technology",
    "SHOP": "Shopify",
    "SPCX": "SpaceX",
    "SBUX": "Starbucks",
    "SNPS": "Synopsys",
    "TMUS": "T-Mobile US",
    "TTWO": "Take-Two Interactive",
    "TER": "Teradyne",
    "TSLA": "Tesla",
    "TXN": "Texas Instruments",
    "TRI": "Thomson Reuters",
    "VRTX": "Vertex Pharmaceuticals",
    "WMT": "Walmart",
    "WBD": "Warner Bros. Discovery",
    "WDC": "Western Digital",
    "WDAY": "Workday",
    "XEL": "Xcel Energy",
}

# Dow Jones Industrial Average constituents: Yahoo Finance ticker -> company name.
DJI30_CONSTITUENTS: dict[str, str] = {
    "MMM": "3M",
    "GOOGL": "Alphabet",
    "AMZN": "Amazon",
    "AXP": "American Express",
    "AMGN": "Amgen",
    "AAPL": "Apple",
    "BA": "Boeing",
    "CAT": "Caterpillar",
    "CVX": "Chevron",
    "CSCO": "Cisco",
    "KO": "Coca-Cola",
    "DIS": "Disney",
    "GS": "Goldman Sachs",
    "HD": "Home Depot",
    "HON": "Honeywell Technologies",
    "IBM": "IBM",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "MCD": "McDonald's",
    "MRK": "Merck",
    "MSFT": "Microsoft",
    "NKE": "Nike",
    "NVDA": "Nvidia",
    "PG": "Procter & Gamble",
    "CRM": "Salesforce",
    "SHW": "Sherwin-Williams",
    "TRV": "Travelers",
    "UNH": "UnitedHealth",
    "V": "Visa",
    "WMT": "Walmart",
}

# DAX constituents: Yahoo Finance ticker -> company name.
DAX_CONSTITUENTS: dict[str, str] = {
    "ADS.DE": "Adidas",
    "AIR.PA": "Airbus",
    "ALV.DE": "Allianz",
    "BAS.DE": "BASF",
    "BAYN.DE": "Bayer",
    "BEI.DE": "Beiersdorf",
    "BMW.DE": "BMW",
    "BNR.DE": "Brenntag",
    "CBK.DE": "Commerzbank",
    "CON.DE": "Continental",
    "DTG.DE": "Daimler Truck",
    "DBK.DE": "Deutsche Bank",
    "DB1.DE": "Deutsche Börse",
    "DHL.DE": "Deutsche Post",
    "DTE.DE": "Deutsche Telekom",
    "EOAN.DE": "E.ON",
    "FRE.DE": "Fresenius",
    "FME.DE": "Fresenius Medical Care",
    "G1A.DE": "GEA Group",
    "HNR1.DE": "Hannover Re",
    "HEI.DE": "Heidelberg Materials",
    "HEN3.DE": "Henkel",
    "IFX.DE": "Infineon Technologies",
    "MBG.DE": "Mercedes-Benz Group",
    "MRK.DE": "Merck",
    "MTX.DE": "MTU Aero Engines",
    "MUV2.DE": "Munich Re",
    "PAH3.DE": "Porsche SE",
    "QIA.DE": "Qiagen",
    "RHM.DE": "Rheinmetall",
    "RWE.DE": "RWE",
    "SAP.DE": "SAP",
    "G24.DE": "Scout24",
    "SIE.DE": "Siemens",
    "ENR.DE": "Siemens Energy",
    "SHL.DE": "Siemens Healthineers",
    "SY1.DE": "Symrise",
    "VOW3.DE": "Volkswagen Group",
    "VNA.DE": "Vonovia",
    "ZAL.DE": "Zalando",
}

# CAC 40 constituents: Yahoo Finance ticker -> company name.
CAC40_CONSTITUENTS: dict[str, str] = {
    "AC.PA": "Accor",
    "AI.PA": "Air Liquide",
    "AIR.PA": "Airbus",
    "MT.AS": "ArcelorMittal",
    "CS.PA": "Axa",
    "BNP.PA": "BNP Paribas",
    "EN.PA": "Bouygues",
    "BVI.PA": "Bureau Veritas",
    "CAP.PA": "Capgemini",
    "CA.PA": "Carrefour",
    "ACA.PA": "Crédit Agricole",
    "BN.PA": "Danone",
    "DSY.PA": "Dassault Systèmes",
    "EDEN.PA": "Edenred",
    "ENGI.PA": "Engie",
    "EL.PA": "EssilorLuxottica",
    "ERF.PA": "Eurofins Scientific",
    "RMS.PA": "Hermès",
    "KER.PA": "Kering",
    "OR.PA": "L'Oréal",
    "LR.PA": "Legrand",
    "MC.PA": "LVMH",
    "ML.PA": "Michelin",
    "ORA.PA": "Orange",
    "RI.PA": "Pernod Ricard",
    "PUB.PA": "Publicis",
    "RNO.PA": "Renault",
    "SAF.PA": "Safran",
    "SGO.PA": "Saint-Gobain",
    "SAN.PA": "Sanofi",
    "SU.PA": "Schneider Electric",
    "GLE.PA": "Société Générale",
    "STLAP.PA": "Stellantis",
    "STMPA.PA": "STMicroelectronics",
    "TEP.PA": "Teleperformance",
    "HO.PA": "Thales",
    "TTE.PA": "TotalEnergies",
    "URW.PA": "Unibail-Rodamco-Westfield",
    "VIE.PA": "Veolia",
    "DG.PA": "Vinci",
}

# Registry: parent index ticker -> its constituents' Yahoo tickers.
# Only indices listed here support constituent-level stages (e.g. breadth confirmation).
INDEX_CONSTITUENTS: dict[str, list[str]] = {
    "^FTSE": list(FTSE100_CONSTITUENTS),
    "^NDX": list(NDX100_CONSTITUENTS),
    "^DJI": list(DJI30_CONSTITUENTS),
    "^GDAXI": list(DAX_CONSTITUENTS),
    "^FCHI": list(CAC40_CONSTITUENTS),
}

# ticker -> name, across all populated indices, for display purposes.
CONSTITUENT_NAMES: dict[str, str] = {
    **FTSE100_CONSTITUENTS,
    **NDX100_CONSTITUENTS,
    **DJI30_CONSTITUENTS,
    **DAX_CONSTITUENTS,
    **CAC40_CONSTITUENTS,
}
