"""Static index constituent lists, needed by stages that score individual stocks
within an index (e.g. breadth confirmation).

There's no free, reliable API for index membership, so these lists are hand-populated
from a public source and refreshed periodically. CONSTITUENTS_SOURCE records where and
when each list was captured, so it's clear when a refresh is due (FTSE Russell reviews
FTSE 100 membership quarterly). If a suitable API/data source becomes available later,
swap the source here - stages only depend on INDEX_CONSTITUENTS, not on how it's built.
"""

CONSTITUENTS_SOURCE: dict[str, str] = {
    "^FTSE": "Wikipedia: en.wikipedia.org/wiki/FTSE_100_Index (captured 2026-08-15)",
}

# FTSE 100 constituents: Yahoo Finance ticker -> company name.
FTSE100_CONSTITUENTS: dict[str, str] = {
    "III.L": "3i",
    "ABDN.L": "Aberdeen Group",
    "ADM.L": "Admiral Group",
    "AAF.L": "Airtel Africa",
    "ALW.L": "Alliance Witan",
    "AAL.L": "Anglo American",
    "ANTO.L": "Antofagasta",
    "ABF.L": "Associated British Foods",
    "AZN.L": "AstraZeneca",
    "AUTO.L": "Autotrader Group",
    "AV.L": "Aviva",
    "BAB.L": "Babcock International",
    "BA.L": "BAE Systems",
    "BARC.L": "Barclays",
    "BTRW.L": "Barratt Redrow",
    "BEZ.L": "Beazley",
    "BP.L": "BP",
    "BATS.L": "British American Tobacco",
    "BLND.L": "British Land",
    "BT-A.L": "BT Group",
    "BNZL.L": "Bunzl",
    "BRBY.L": "Burberry Group",
    "CNA.L": "Centrica",
    "CCEP.L": "Coca-Cola Europacific Partners",
    "CCH.L": "Coca-Cola HBC",
    "CPG.L": "Compass Group",
    "CCC.L": "Computacenter",
    "CTEC.L": "Convatec",
    "CRDA.L": "Croda International",
    "DCC.L": "DCC",
    "DGE.L": "Diageo",
    "DPLM.L": "Diploma",
    "EDV.L": "Endeavour Mining",
    "ENT.L": "Entain",
    "EXPN.L": "Experian",
    "FCIT.L": "F&C Investment Trust",
    "FRES.L": "Fresnillo",
    "GAW.L": "Games Workshop",
    "GLEN.L": "Glencore",
    "GSK.L": "GSK",
    "HLN.L": "Haleon",
    "HLMA.L": "Halma",
    "HSX.L": "Hiscox",
    "HWDN.L": "Howdens Joinery",
    "HSBA.L": "HSBC",
    "ICG.L": "ICG",
    "IGG.L": "IG Group",
    "IHG.L": "IHG Hotels & Resorts",
    "IMI.L": "IMI",
    "IMB.L": "Imperial Brands",
    "INF.L": "Informa",
    "IAG.L": "International Airlines Group",
    "ITRK.L": "Intertek",
    "INVP.L": "Investec",
    "JD.L": "JD Sports",
    "BGEO.L": "Lion Finance Group",
    "KGF.L": "Kingfisher",
    "LAND.L": "Land Securities",
    "LGEN.L": "Legal & General",
    "LLOY.L": "Lloyds Banking Group",
    "LMP.L": "LondonMetric Property",
    "LSEG.L": "London Stock Exchange Group",
    "MNG.L": "M&G",
    "MKS.L": "Marks & Spencer",
    "MRO.L": "Melrose Industries",
    "MTLN.L": "Metlen Energy & Metals",
    "NG.L": "National Grid",
    "NWG.L": "NatWest Group",
    "NXT.L": "Next",
    "PSON.L": "Pearson",
    "PSH.L": "Pershing Square Holdings",
    "PSN.L": "Persimmon",
    "PCT.L": "Polar Capital Technology Trust",
    "PRU.L": "Prudential",
    "RKT.L": "Reckitt",
    "REL.L": "RELX",
    "RTO.L": "Rentokil Initial",
    "RIO.L": "Rio Tinto",
    "RR.L": "Rolls-Royce Holdings",
    "SGE.L": "Sage Group",
    "SBRY.L": "Sainsbury's",
    "SDR.L": "Schroders",
    "SMT.L": "Scottish Mortgage Investment Trust",
    "SGRO.L": "Segro",
    "SVT.L": "Severn Trent",
    "SHEL.L": "Shell",
    "SMIN.L": "Smiths Group",
    "SN.L": "Smith & Nephew",
    "SPX.L": "Spirax Group",
    "SSE.L": "SSE",
    "STAN.L": "Standard Chartered",
    "SDLF.L": "Standard Life",
    "STJ.L": "St. James's Place",
    "TSCO.L": "Tesco",
    "BBOX.L": "Tritax Big Box REIT",
    "ULVR.L": "Unilever",
    "UU.L": "United Utilities",
    "VOD.L": "Vodafone Group",
    "WEIR.L": "Weir",
    "WTB.L": "Whitbread",
}

# Registry: parent index ticker -> its constituents' Yahoo tickers.
# Only indices listed here support constituent-level stages (e.g. breadth confirmation).
INDEX_CONSTITUENTS: dict[str, list[str]] = {
    "^FTSE": list(FTSE100_CONSTITUENTS),
}

# ticker -> name, across all populated indices, for display purposes.
CONSTITUENT_NAMES: dict[str, str] = {**FTSE100_CONSTITUENTS}
